sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aminefradi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aminefradi/docker-react npm run test

after_success:
  - docker build -t aminefradi/multi-client ./client
  - docker build -t aminefradi/multi-nginx ./nginx
  - docker build -t aminefradi/multi-server ./server
  - docker build -t aminefradi/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push aminefradi/multi-client
  - docker push aminefradi/multi-nginx
  - docker push aminefradi/multi-server
  - docker push aminefradi/multi-worker

#deploy:
  #provider: elasticbeanstalk
  #region: us-west-1
  #app: multi-docker
  #env: MultiDocker-env
  #bucket_name: elasticbeanstalk-us-west-1-306476627547
  #bucket_path: docker-multi
  #on:
    #branch: master
  #access_key_id: $AWS_ACCESS_KEY
  #secret_access_key: $AWS_SECRET_KEY
